[15/Jul/2023 17:02:51] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 38, in admin_deposit_simba
    d_account = Account.objects.get(account_number=account)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
savings.models.Account.DoesNotExist: Account matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 40, in admin_deposit_simba
    except Account.DoesNot.Exist:
AttributeError: type object 'Account' has no attribute 'DoesNot'
[15/Jul/2023 17:02:51] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 85054
[15/Jul/2023 17:04:50] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 38, in admin_deposit_simba
    d_account = Account.objects.get(account_number=account)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
savings.models.Account.DoesNotExist: Account matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 42, in admin_deposit_simba
    return redirect("admin_deposit_simba")
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin_deposit_simba' not found. 'admin_deposit_simba' is not a valid view function or pattern name.
[15/Jul/2023 17:04:50] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 103661
[15/Jul/2023 17:09:06] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 38, in admin_deposit_simba
    d_account = Account.objects.get(account_number=account)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
savings.models.Account.DoesNotExist: Account matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 42, in admin_deposit_simba
    return redirect("admin_deposit_simba")
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin_deposit_simba' not found. 'admin_deposit_simba' is not a valid view function or pattern name.
[15/Jul/2023 17:09:06] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 103908
[15/Jul/2023 17:16:48] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 32, in admin_deposit_simba
    status = not_negative(deposit_amount)
  File "/home/dennis/projects/saving_record/savingrecord/savings/classes.py", line 73, in not_negative
    if int(amount) > 0:
ValueError: invalid literal for int() with base 10: 'hjjkk'
[15/Jul/2023 17:16:48] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 74261
[15/Jul/2023 17:35:26] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 38, in admin_deposit_simba
    return redirect("userdata:admin_withdraw_simba")
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin_withdraw_simba' not found. 'admin_withdraw_simba' is not a valid view function or pattern name.
[15/Jul/2023 17:35:26] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 90736
[15/Jul/2023 17:54:33] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 33, in admin_deposit_simba
    deposit_amount = Decimal(amount)
NameError: name 'Decimal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 34, in admin_deposit_simba
    except InvalidOperation as e:
NameError: name 'InvalidOperation' is not defined
[15/Jul/2023 17:54:33] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 75457
[15/Jul/2023 17:56:03] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 34, in admin_deposit_simba
    deposit_amount = Decimal(amount)
NameError: name 'amount' is not defined
[15/Jul/2023 17:56:03] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 70815
[15/Jul/2023 17:56:48] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 17:56:48] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69843
[15/Jul/2023 18:01:09] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 34, in admin_deposit_simba
    deposit_amount = Decimal(deposit_amount)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 35, in admin_deposit_simba
    except decimal.InvalidOperation:
NameError: name 'decimal' is not defined
[15/Jul/2023 18:01:09] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 75480
[15/Jul/2023 18:05:49] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:05:49] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69843
[15/Jul/2023 18:09:19] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:09:19] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69843
[15/Jul/2023 18:10:25] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 34, in admin_deposit_simba
    status = not_negative(deposit_amount)
  File "/home/dennis/projects/saving_record/savingrecord/savings/classes.py", line 72, in not_negative
    if int(amount) > 0:
ValueError: invalid literal for int() with base 10: 'hjjkk'
[15/Jul/2023 18:10:25] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 74456
[15/Jul/2023 18:16:25] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 35, in admin_deposit_simba
    if status == "negative":
NameError: name 'status' is not defined
[15/Jul/2023 18:16:25] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 70955
[15/Jul/2023 18:17:51] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:17:51] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69843
[15/Jul/2023 18:18:50] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:18:50] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69841
[15/Jul/2023 18:20:55] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:20:55] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69841
[15/Jul/2023 18:23:07] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 54, in admin_deposit_simba
    d_account.account_balance += Decimal(deposit_amount)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
[15/Jul/2023 18:23:07] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 71686
[15/Jul/2023 18:26:31] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
[15/Jul/2023 18:26:31] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 69833
[15/Jul/2023 18:56:09] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'deposit_amount'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 30, in admin_deposit_simba
    deposit_amount = request.POST["deposit_amount"]
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'deposit_amount'
[15/Jul/2023 18:56:09] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 79031
[15/Jul/2023 18:58:31] ERROR [django.request:241] Internal Server Error: /operations/admin_deposit
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'deposit_amount'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 30, in admin_deposit_simba
    deposit_amount = request.POST["deposit_amount"]
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'deposit_amount'
[15/Jul/2023 18:58:31] ERROR [django.server:212] "POST /operations/admin_deposit HTTP/1.1" 500 79031
[15/Jul/2023 19:00:26] ERROR [django.request:241] Internal Server Error: /operations/admin_withdraw
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 120, in admin_widthdraw
    return render(request, "userdata/admin_withdraw_simba.html", {})
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'staff' not found. 'staff' is not a valid view function or pattern name.
[15/Jul/2023 19:00:26] ERROR [django.server:212] "GET /operations/admin_withdraw HTTP/1.1" 500 171419
[15/Jul/2023 19:01:28] ERROR [django.request:241] Internal Server Error: /operations/admin_withdraw
Traceback (most recent call last):
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/dennis/projects/saving_record/saving/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennis/projects/saving_record/savingrecord/userdata/views.py", line 109, in admin_widthdraw
    w_account.total_deposit -= deposit_amount
NameError: name 'deposit_amount' is not defined
[15/Jul/2023 19:01:28] ERROR [django.server:212] "POST /operations/admin_withdraw HTTP/1.1" 500 71952
